name: MISW4101-202314-Grupo042

# Controls when the action will run. 
on:
  push:
    branches:   
      - develop 
      - 'ENFORMA-HU**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  correr-pruebas:
    name: Pruebas 
    runs-on: ubuntu-latest
    outputs:
      respuesta: ${{ steps.correr-pruebas.outputs.respuesta }}
      accion: ${{ steps.correr-pruebas.outputs.accion }}
    steps:
    - name: Validar mensaje de HU implementada
      if: ${{ contains(github.event.head_commit.message, 'Hecho') }}
      env:
        ACCION: Merge a develop
      run: echo "::set-output name=accion::${ACCION}"
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Validar resultado con errores
      if: ${{ failure() }}
      run: exit(1)
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    - name: Nombre para identificar la rama
      if: ${{github.ref=='develop' }}
      run: echo "Mensaje de HU implementada válido"
  Mi-segundo-job:
    needs: correr-pruebas
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.correr-pruebas.outputs.accion}}
    - name: Verificar accion
      if: ${{needs.correr-pruebas.outputs.accion == 'Merge a develop' && contains(github.ref, 'ENFORMA-HU') }} 
      run: echo "Se puede hacer merge a develop"
    - name: Verificar accion release
      if: ${{needs.correr-pruebas.outputs.accion == 'Generar release'}} 
      run: echo "Se puede generar release"
    - name: Imprimir respuesta
      id: imprimir-respuesta
      run: echo ${{needs.correr-pruebas.outputs.respuesta}}