name: Merge de Develop

# Controls when the action will run. 
on:
  push:
    branches:
      - 'ENFORMA-HU**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Correr-Pruebas:
    name: Pruebas 
    runs-on: ubuntu-latest
    outputs:
      respuesta: ${{ steps.correr-pruebas.outputs.respuesta }}
      accion: ${{ steps.validar-mensaje.outputs.accion }}
    steps:
    - name: Validar mensaje de HU implementada
      id: validar-mensaje
      if: ${{ contains(github.event.head_commit.message, 'Hecho') }}
      env:
        ACCION: Merge de develop
      run: echo "::set-output name=accion::${ACCION}"

  Mi-segundo-job:
    needs: Correr-Pruebas
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout de repositorio
      uses: actions/checkout@v2

    - name: Mezcla RamaFeature -> develop y corre pruebas
      if: ${{needs.Correr-Pruebas.outputs.accion == 'Merge de develop' }} 
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{github.ref}}
        
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        ls
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado sin errores
      if: ${{ success() && needs.Correr-Pruebas.outputs.accion == 'Merge de develop' }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{github.ref}}
        target-branch: develop
    
      
